import React from "react";

import "./App.scss";

import type { Metadata } from "next";
import { GlobalizationAndHeader } from "./globalization-and-header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          data-kendo="true"
          href={`https://cdn.kendostatic.com/themes/7.0.1/default/default-main.css`}
        />
      </head>
      <body>
        <GlobalizationAndHeader>{children}</GlobalizationAndHeader>
      </body>
    </html>
  );
}
