export default [
    'The Godfather',
    'The Shawshank Redemption',
    'Pulp Fiction',
    'The Dark Knight',
    'Forrest Gump',
    'Inception',
    'The Matrix',
    'Fight Club',
    'Goodfellas',
    'The Lord of the Rings: The Fellowship of the Ring',
    'The Lord of the Rings: The Two Towers',
    'The Lord of the Rings: The Return of the King',
    'Star Wars: A New Hope',
    'Star Wars: The Empire Strikes Back',
    'Star Wars: Return of the Jedi',
    'Interstellar',
    'Schindler’s List',
    'Gladiator',
    'The Silence of the Lambs',
    'Titanic',
    'The Green Mile',
    'Saving Private Ryan',
    'Django Unchained',
    'The Departed',
    'The Prestige',
    'The Lion King',
    'Spirited Away',
    'Avengers: Endgame',
    'Avatar',
    'Parasite',
    'Joker',
    'The Truman Show',
    'Back to the Future',
    'Jurassic Park',
    'The Grand Budapest Hotel',
    'No Country for Old Men',
    'The Big Lebowski',
    'Se7en',
    'Whiplash',
    'A Clockwork Orange',
    'Casablanca',
    '12 Angry Men',
    'Requiem for a Dream',
    'Amélie',
    'The Revenant',
    'Blade Runner 2049',
    'The Wolf of Wall Street',
    'Black Panther',
    'The Social Network',
    'La La Land'
];
