export default [
    '1984',
    'Pride and Prejudice',
    'To Kill a Mockingbird',
    'The Great Gatsby',
    'Moby-Dick',
    'War and Peace',
    'The Catcher in the Rye',
    'Brave New World',
    'The Lord of the Rings',
    'Crime and Punishment',
    'Jane Eyre',
    'Wuthering Heights',
    'The Hobbit',
    'Anna Karenina',
    'Fahrenheit 451',
    'Don Quixote',
    'Les Misérables',
    'Dracula',
    'Frankenstein',
    'The Picture of Dorian Gray',
    'The Brothers Karamazov',
    'The Count of Monte Cristo',
    'A Tale of Two Cities',
    'The Alchemist',
    'Slaughterhouse-Five',
    'One Hundred Years of Solitude',
    'The Grapes of Wrath',
    'The Road',
    'Catch-22',
    'Ulysses',
    'The Old Man and the Sea',
    'The Divine Comedy',
    'The Stranger',
    'Alice’s Adventures in Wonderland',
    'The Little Prince',
    'The Secret Garden',
    'Charlotte’s Web',
    'Great Expectations',
    'David Copperfield',
    'Middlemarch',
    'The Scarlet Letter',
    'The Sun Also Rises',
    'Beloved',
    'Lolita',
    'Madame Bovary',
    'Gone with the Wind',
    'The Name of the Wind',
    'Dune',
    'The Hitchhiker’s Guide to the Galaxy',
    'Harry Potter and the Sorcerer’s Stone'
];
