/**
 * E-Commerce Product Demo Data
 *
 * This file contains comprehensive mock e-commerce product data designed for retail
 * and product management applications. The dataset includes 50 realistic products
 * spanning multiple categories and international suppliers.
 */

export enum ProductCategory {
    Electronics = 'Electronics',
    Clothing = 'Clothing',
    HomeGarden = 'Home & Garden',
    Sports = 'Sports & Outdoors',
    Books = 'Books & Media',
    Health = 'Health & Beauty',
    Toys = 'Toys & Games',
    Automotive = 'Automotive',
    Food = 'Food & Beverages',
    Office = 'Office Supplies'
}

export enum StockStatus {
    InStock = 'In Stock',
    LowStock = 'Low Stock',
    OutOfStock = 'Out of Stock',
    Discontinued = 'Discontinued',
    PreOrder = 'Pre-Order',
    BackOrder = 'Back Order'
}

export enum ShippingMethod {
    Standard = 'Standard',
    Express = 'Express',
    Freight = 'Freight',
    Overnight = 'Overnight',
    PickupOnly = 'Pickup Only'
}

export interface Product {
    id: number;
    sku: string;
    name: string;
    description: string;
    category: ProductCategory;
    price: number;
    salePrice?: number;
    inStock: boolean;
    tags: string[];
    createdDate: Date;
    lastModified: Date;
    stockQuantity: number;
    stockStatus: StockStatus;
    rating: number;
    reviewCount: number;
    onSale: boolean;
    weight: number;
    brand: string;
    model: string;
    countryOfOrigin: string;
    shipping: {
        method: ShippingMethod;
        cost: number;
        estimatedDays: number;
    };
}

const currentYear = new Date().getFullYear() - 1;

export const products: Product[] = [
    {
        id: 1,
        sku: 'ELEC-001',
        name: 'Wireless Bluetooth Headphones',
        description: 'Premium noise-cancelling wireless headphones with 30-hour battery life',
        category: ProductCategory.Electronics,
        price: 299.99,
        salePrice: 249.99,
        inStock: true,
        tags: ['wireless', 'bluetooth', 'noise-cancelling', 'premium'],
        createdDate: new Date(currentYear, 0, 15),
        lastModified: new Date(currentYear, 1, 20),
        stockQuantity: 45,
        stockStatus: StockStatus.InStock,
        rating: 4.8,
        reviewCount: 324,
        onSale: true,
        weight: 0.25,
        brand: 'AudioTech',
        model: 'AT-WH300',
        countryOfOrigin: 'South Korea',
        shipping: {
            method: ShippingMethod.Express,
            cost: 9.99,
            estimatedDays: 2
        }
    },
    {
        id: 2,
        sku: 'CLOTH-001',
        name: 'Organic Cotton T-Shirt',
        description: 'Comfortable organic cotton t-shirt with sustainable manufacturing',
        category: ProductCategory.Clothing,
        price: 34.99,
        inStock: true,
        tags: ['organic', 'cotton', 'sustainable', 'casual'],
        createdDate: new Date(currentYear, 1, 10),
        lastModified: new Date(currentYear, 2, 15),
        stockQuantity: 128,
        stockStatus: StockStatus.InStock,
        rating: 4.5,
        reviewCount: 89,
        onSale: false,
        weight: 0.15,
        brand: 'EcoWear',
        model: 'ECO-TEE-001',
        countryOfOrigin: 'Portugal',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 4.99,
            estimatedDays: 5
        }
    },
    {
        id: 3,
        sku: 'HOME-001',
        name: 'Smart Plant Watering System',
        description: 'Automated plant care system with moisture sensors and app control',
        category: ProductCategory.HomeGarden,
        price: 149.99,
        salePrice: 119.99,
        inStock: false,
        tags: ['smart', 'gardening', 'automation', 'plants'],
        createdDate: new Date(currentYear, 2, 5),
        lastModified: new Date(currentYear, 3, 10),
        stockQuantity: 0,
        stockStatus: StockStatus.OutOfStock,
        rating: 2.8,
        reviewCount: 156,
        onSale: true,
        weight: 1.2,
        brand: 'GreenTech',
        model: 'GT-PWS-100',
        countryOfOrigin: 'Netherlands',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 12.99,
            estimatedDays: 7
        }
    },
    {
        id: 4,
        sku: 'SPORTS-001',
        name: 'Professional Tennis Racket',
        description: 'High-performance tennis racket designed for competitive play',
        category: ProductCategory.Sports,
        price: 189.99,
        salePrice: 159.99,
        inStock: true,
        tags: ['tennis', 'professional', 'sports', 'competition'],
        createdDate: new Date(currentYear, 3, 12),
        lastModified: new Date(currentYear, 4, 8),
        stockQuantity: 32,
        stockStatus: StockStatus.InStock,
        rating: 4.6,
        reviewCount: 78,
        onSale: true,
        weight: 0.31,
        brand: 'SportsPro',
        model: 'SP-TR-2024',
        countryOfOrigin: 'Japan',
        shipping: {
            method: ShippingMethod.Express,
            cost: 8.99,
            estimatedDays: 3
        }
    },
    {
        id: 5,
        sku: 'BOOKS-001',
        name: 'Digital Photography Guide',
        description: 'Comprehensive guide to modern digital photography techniques',
        category: ProductCategory.Books,
        price: 24.99,
        inStock: true,
        tags: ['photography', 'digital', 'education', 'guide'],
        createdDate: new Date(currentYear, 4, 18),
        lastModified: new Date(currentYear, 5, 2),
        stockQuantity: 95,
        stockStatus: StockStatus.InStock,
        rating: 4.7,
        reviewCount: 142,
        onSale: false,
        weight: 0.45,
        brand: 'TechBooks',
        model: 'TB-DPG-001',
        countryOfOrigin: 'United States',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 3.99,
            estimatedDays: 4
        }
    },
    {
        id: 6,
        sku: 'HEALTH-001',
        name: 'Vitamin D3 Supplements',
        description: 'High-potency vitamin D3 capsules for bone and immune health',
        category: ProductCategory.Health,
        price: 19.99,
        inStock: true,
        tags: ['vitamins', 'health', 'supplements', 'immune'],
        createdDate: new Date(currentYear, 5, 10),
        lastModified: new Date(currentYear, 6, 5),
        stockQuantity: 200,
        stockStatus: StockStatus.InStock,
        rating: 4.4,
        reviewCount: 67,
        onSale: false,
        weight: 0.08,
        brand: 'HealthPlus',
        model: 'HP-D3-1000',
        countryOfOrigin: 'Canada',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 2.99,
            estimatedDays: 6
        }
    },
    {
        id: 7,
        sku: 'TOY-001',
        name: 'Educational Building Blocks',
        description: 'Colorful wooden building blocks for creative learning and development',
        category: ProductCategory.Toys,
        price: 49.99,
        salePrice: 39.99,
        inStock: true,
        tags: ['educational', 'wooden', 'creative', 'learning'],
        createdDate: new Date(currentYear, 6, 20),
        lastModified: new Date(currentYear, 7, 15),
        stockQuantity: 75,
        stockStatus: StockStatus.InStock,
        rating: 4.9,
        reviewCount: 134,
        onSale: true,
        weight: 1.5,
        brand: 'PlaySmart',
        model: 'PS-BB-200',
        countryOfOrigin: 'Germany',
        shipping: {
            method: ShippingMethod.Express,
            cost: 7.99,
            estimatedDays: 2
        }
    },
    {
        id: 8,
        sku: 'AUTO-001',
        name: 'Car Phone Mount',
        description: 'Universal magnetic car phone mount with 360-degree rotation',
        category: ProductCategory.Automotive,
        price: 29.99,
        inStock: true,
        tags: ['car', 'phone', 'mount', 'magnetic'],
        createdDate: new Date(currentYear, 7, 8),
        lastModified: new Date(currentYear, 8, 12),
        stockQuantity: 156,
        stockStatus: StockStatus.InStock,
        rating: 3.2,
        reviewCount: 98,
        onSale: false,
        weight: 0.2,
        brand: 'CarTech',
        model: 'CT-PM-360',
        countryOfOrigin: 'China',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 5.99,
            estimatedDays: 5
        }
    },
    {
        id: 9,
        sku: 'FOOD-001',
        name: 'Organic Coffee Beans',
        description: 'Premium organic coffee beans from sustainable farms',
        category: ProductCategory.Food,
        price: 16.99,
        inStock: true,
        tags: ['organic', 'coffee', 'premium', 'sustainable'],
        createdDate: new Date(currentYear, 8, 1),
        lastModified: new Date(currentYear, 9, 5),
        stockQuantity: 84,
        stockStatus: StockStatus.InStock,
        rating: 4.6,
        reviewCount: 112,
        onSale: false,
        weight: 0.5,
        brand: 'BeanCraft',
        model: 'BC-ORG-500',
        countryOfOrigin: 'Colombia',
        shipping: {
            method: ShippingMethod.Express,
            cost: 6.99,
            estimatedDays: 3
        }
    },
    {
        id: 10,
        sku: 'OFFICE-001',
        name: 'Ergonomic Desk Chair',
        description: 'Comfortable ergonomic office chair with lumbar support',
        category: ProductCategory.Office,
        price: 299.99,
        salePrice: 249.99,
        inStock: true,
        tags: ['ergonomic', 'office', 'chair', 'comfort'],
        createdDate: new Date(currentYear, 9, 12),
        lastModified: new Date(currentYear, 10, 8),
        stockQuantity: 28,
        stockStatus: StockStatus.LowStock,
        rating: 4.5,
        reviewCount: 87,
        onSale: true,
        weight: 18.5,
        brand: 'OfficeComfort',
        model: 'OC-EC-2024',
        countryOfOrigin: 'Taiwan',
        shipping: {
            method: ShippingMethod.Freight,
            cost: 49.99,
            estimatedDays: 10
        }
    },
    {
        id: 11,
        sku: 'ELEC-002',
        name: 'Smart Fitness Watch',
        description: 'Advanced fitness tracker with heart rate monitoring and GPS',
        category: ProductCategory.Electronics,
        price: 199.99,
        salePrice: 179.99,
        inStock: true,
        tags: ['fitness', 'smart', 'gps', 'health'],
        createdDate: new Date(currentYear, 10, 5),
        lastModified: new Date(currentYear, 11, 2),
        stockQuantity: 67,
        stockStatus: StockStatus.InStock,
        rating: 4.3,
        reviewCount: 203,
        onSale: true,
        weight: 0.05,
        brand: 'TechPower',
        model: 'TP-FW-100',
        countryOfOrigin: 'South Korea',
        shipping: {
            method: ShippingMethod.Express,
            cost: 7.99,
            estimatedDays: 2
        }
    },
    {
        id: 12,
        sku: 'ELEC-003',
        name: 'Portable Power Bank',
        description: 'High-capacity portable charger with fast charging technology',
        category: ProductCategory.Electronics,
        price: 59.99,
        inStock: false,
        tags: ['portable', 'charging', 'battery', 'fast'],
        createdDate: new Date(currentYear, 2, 20),
        lastModified: new Date(currentYear, 3, 15),
        stockQuantity: 0,
        stockStatus: StockStatus.OutOfStock,
        rating: 3.1,
        reviewCount: 145,
        onSale: false,
        weight: 0.4,
        brand: 'TechPower',
        model: 'TP-PB-20K',
        countryOfOrigin: 'China',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 5.99,
            estimatedDays: 5
        }
    },
    {
        id: 13,
        sku: 'CLOTH-002',
        name: 'Denim Jacket',
        description: 'Classic denim jacket with vintage wash and modern fit',
        category: ProductCategory.Clothing,
        price: 89.99,
        salePrice: 69.99,
        inStock: true,
        tags: ['denim', 'jacket', 'vintage', 'classic'],
        createdDate: new Date(currentYear, 1, 25),
        lastModified: new Date(currentYear, 2, 10),
        stockQuantity: 42,
        stockStatus: StockStatus.InStock,
        rating: 4.4,
        reviewCount: 76,
        onSale: true,
        weight: 0.8,
        brand: 'EcoWear',
        model: 'ECO-DJ-001',
        countryOfOrigin: 'Portugal',
        shipping: {
            method: ShippingMethod.Express,
            cost: 8.99,
            estimatedDays: 3
        }
    },
    {
        id: 14,
        sku: 'SPORTS-003',
        name: 'Running Shoes',
        description: 'Lightweight running shoes with advanced cushioning technology',
        category: ProductCategory.Sports,
        price: 129.99,
        inStock: true,
        tags: ['running', 'shoes', 'lightweight', 'cushioning'],
        createdDate: new Date(currentYear, 3, 8),
        lastModified: new Date(currentYear, 4, 12),
        stockQuantity: 89,
        stockStatus: StockStatus.InStock,
        rating: 4.7,
        reviewCount: 234,
        onSale: false,
        weight: 0.6,
        brand: 'SportsPro',
        model: 'SP-RS-2024',
        countryOfOrigin: 'Vietnam',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 6.99,
            estimatedDays: 4
        }
    },
    {
        id: 15,
        sku: 'HOME-002',
        name: 'LED Desk Lamp',
        description: 'Adjustable LED desk lamp with touch controls and USB charging',
        category: ProductCategory.HomeGarden,
        price: 79.99,
        salePrice: 59.99,
        inStock: true,
        tags: ['led', 'desk', 'lamp', 'adjustable'],
        createdDate: new Date(currentYear, 4, 15),
        lastModified: new Date(currentYear, 5, 20),
        stockQuantity: 156,
        stockStatus: StockStatus.InStock,
        rating: 4.2,
        reviewCount: 98,
        onSale: true,
        weight: 1.1,
        brand: 'GreenTech',
        model: 'GT-DL-200',
        countryOfOrigin: 'Netherlands',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 9.99,
            estimatedDays: 6
        }
    },
    {
        id: 16,
        sku: 'SPORTS-002',
        name: 'Yoga Mat',
        description: 'Premium non-slip yoga mat with eco-friendly materials',
        category: ProductCategory.Sports,
        price: 39.99,
        inStock: true,
        tags: ['yoga', 'mat', 'non-slip', 'eco-friendly'],
        createdDate: new Date(currentYear, 5, 3),
        lastModified: new Date(currentYear, 6, 8),
        stockQuantity: 203,
        stockStatus: StockStatus.InStock,
        rating: 4.5,
        reviewCount: 167,
        onSale: false,
        weight: 1.2,
        brand: 'FitLife',
        model: 'FL-YM-PRO',
        countryOfOrigin: 'India',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 7.99,
            estimatedDays: 5
        }
    },
    {
        id: 17,
        sku: 'SPORTS-004',
        name: 'Basketball',
        description: 'Official size basketball with superior grip and durability',
        category: ProductCategory.Sports,
        price: 29.99,
        salePrice: 24.99,
        inStock: true,
        tags: ['basketball', 'official', 'grip', 'durable'],
        createdDate: new Date(currentYear, 6, 12),
        lastModified: new Date(currentYear, 7, 5),
        stockQuantity: 178,
        stockStatus: StockStatus.InStock,
        rating: 4.3,
        reviewCount: 89,
        onSale: true,
        weight: 0.62,
        brand: 'SportsPro',
        model: 'SP-BB-OFC',
        countryOfOrigin: 'Japan',
        shipping: {
            method: ShippingMethod.Express,
            cost: 5.99,
            estimatedDays: 2
        }
    },
    {
        id: 18,
        sku: 'BOOKS-002',
        name: 'Web Development Handbook',
        description: 'Complete guide to modern web development frameworks and tools',
        category: ProductCategory.Books,
        price: 39.99,
        salePrice: 29.99,
        inStock: false,
        tags: ['web', 'development', 'programming', 'frameworks'],
        createdDate: new Date(currentYear, 7, 22),
        lastModified: new Date(currentYear, 8, 18),
        stockQuantity: 0,
        stockStatus: StockStatus.PreOrder,
        rating: 4.8,
        reviewCount: 245,
        onSale: true,
        weight: 0.52,
        brand: 'TechBooks',
        model: 'TB-WDH-2024',
        countryOfOrigin: 'United States',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 4.99,
            estimatedDays: 8
        }
    },
    {
        id: 19,
        sku: 'HEALTH-002',
        name: 'Protein Powder',
        description: 'Whey protein powder for muscle building and recovery',
        category: ProductCategory.Health,
        price: 49.99,
        inStock: true,
        tags: ['protein', 'whey', 'muscle', 'recovery'],
        createdDate: new Date(currentYear, 8, 10),
        lastModified: new Date(currentYear, 9, 12),
        stockQuantity: 134,
        stockStatus: StockStatus.InStock,
        rating: 4.4,
        reviewCount: 189,
        onSale: false,
        weight: 2.27,
        brand: 'HealthPlus',
        model: 'HP-WP-2000',
        countryOfOrigin: 'Canada',
        shipping: {
            method: ShippingMethod.Express,
            cost: 12.99,
            estimatedDays: 3
        }
    },
    {
        id: 20,
        sku: 'TOY-002',
        name: 'Remote Control Drone',
        description: 'Beginner-friendly drone with camera and obstacle avoidance',
        category: ProductCategory.Toys,
        price: 199.99,
        salePrice: 149.99,
        inStock: true,
        tags: ['drone', 'remote', 'camera', 'beginner'],
        createdDate: new Date(currentYear, 9, 5),
        lastModified: new Date(currentYear, 10, 15),
        stockQuantity: 23,
        stockStatus: StockStatus.LowStock,
        rating: 2.1,
        reviewCount: 78,
        onSale: true,
        weight: 0.85,
        brand: 'TechToys',
        model: 'TT-DR-100',
        countryOfOrigin: 'China',
        shipping: {
            method: ShippingMethod.Express,
            cost: 11.99,
            estimatedDays: 2
        }
    },
    {
        id: 21,
        sku: 'AUTO-002',
        name: 'Car Air Freshener',
        description: 'Long-lasting car air freshener with natural vanilla scent',
        category: ProductCategory.Automotive,
        price: 8.99,
        inStock: true,
        tags: ['air', 'freshener', 'vanilla', 'natural'],
        createdDate: new Date(currentYear, 10, 18),
        lastModified: new Date(currentYear, 11, 5),
        stockQuantity: 345,
        stockStatus: StockStatus.InStock,
        rating: 2.4,
        reviewCount: 124,
        onSale: false,
        weight: 0.05,
        brand: 'CarTech',
        model: 'CT-AF-VAN',
        countryOfOrigin: 'China',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 2.99,
            estimatedDays: 6
        }
    },
    {
        id: 22,
        sku: 'FOOD-002',
        name: 'Green Tea',
        description: 'Premium loose leaf green tea with antioxidants',
        category: ProductCategory.Food,
        price: 22.99,
        salePrice: 18.99,
        inStock: true,
        tags: ['green', 'tea', 'antioxidants', 'premium'],
        createdDate: new Date(currentYear, 0, 8),
        lastModified: new Date(currentYear, 1, 15),
        stockQuantity: 167,
        stockStatus: StockStatus.InStock,
        rating: 4.6,
        reviewCount: 156,
        onSale: true,
        weight: 0.25,
        brand: 'BeanCraft',
        model: 'BC-GT-250',
        countryOfOrigin: 'Japan',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 4.99,
            estimatedDays: 5
        }
    },
    {
        id: 23,
        sku: 'OFFICE-002',
        name: 'Wireless Keyboard',
        description: 'Compact wireless keyboard with mechanical switches',
        category: ProductCategory.Office,
        price: 89.99,
        inStock: false,
        tags: ['wireless', 'keyboard', 'mechanical', 'compact'],
        createdDate: new Date(currentYear, 1, 28),
        lastModified: new Date(currentYear, 2, 25),
        stockQuantity: 0,
        stockStatus: StockStatus.BackOrder,
        rating: 4.5,
        reviewCount: 234,
        onSale: false,
        weight: 0.75,
        brand: 'OfficeComfort',
        model: 'OC-WK-2024',
        countryOfOrigin: 'Taiwan',
        shipping: {
            method: ShippingMethod.Express,
            cost: 8.99,
            estimatedDays: 14
        }
    },
    {
        id: 24,
        sku: 'ELEC-004',
        name: 'Smartphone Case',
        description: 'Protective smartphone case with military-grade drop protection',
        category: ProductCategory.Electronics,
        price: 24.99,
        inStock: true,
        tags: ['smartphone', 'case', 'protection', 'military'],
        createdDate: new Date(currentYear, 2, 14),
        lastModified: new Date(currentYear, 3, 8),
        stockQuantity: 289,
        stockStatus: StockStatus.InStock,
        rating: 4.2,
        reviewCount: 167,
        onSale: false,
        weight: 0.12,
        brand: 'TechPower',
        model: 'TP-SC-MIL',
        countryOfOrigin: 'China',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 3.99,
            estimatedDays: 4
        }
    },
    {
        id: 25,
        sku: 'CLOTH-004',
        name: 'Winter Sweater',
        description: 'Warm wool sweater with classic cable knit pattern',
        category: ProductCategory.Clothing,
        price: 79.99,
        inStock: true,
        tags: ['winter', 'sweater', 'wool', 'cable-knit'],
        createdDate: new Date(currentYear, 11, 1),
        lastModified: new Date(currentYear, 11, 20),
        stockQuantity: 56,
        stockStatus: StockStatus.InStock,
        rating: 4.7,
        reviewCount: 112,
        onSale: false,
        weight: 0.65,
        brand: 'EcoWear',
        model: 'ECO-WS-001',
        countryOfOrigin: 'Ireland',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 7.99,
            estimatedDays: 5
        }
    },
    {
        id: 26,
        sku: 'HOME-003',
        name: 'Coffee Maker',
        description: 'Programmable coffee maker with thermal carafe and auto-brew',
        category: ProductCategory.HomeGarden,
        price: 159.99,
        salePrice: 129.99,
        inStock: true,
        tags: ['coffee', 'maker', 'programmable', 'thermal'],
        createdDate: new Date(currentYear, 0, 20),
        lastModified: new Date(currentYear, 1, 12),
        stockQuantity: 78,
        stockStatus: StockStatus.InStock,
        rating: 4.3,
        reviewCount: 203,
        onSale: true,
        weight: 4.5,
        brand: 'KitchenPro',
        model: 'KP-CM-12',
        countryOfOrigin: 'Germany',
        shipping: {
            method: ShippingMethod.Freight,
            cost: 24.99,
            estimatedDays: 8
        }
    },
    {
        id: 27,
        sku: 'HEALTH-003',
        name: 'Multivitamin Tablets',
        description: 'Complete daily multivitamin with essential minerals',
        category: ProductCategory.Health,
        price: 29.99,
        inStock: true,
        tags: ['multivitamin', 'daily', 'minerals', 'essential'],
        createdDate: new Date(currentYear, 3, 16),
        lastModified: new Date(currentYear, 4, 22),
        stockQuantity: 267,
        stockStatus: StockStatus.InStock,
        rating: 3.6,
        reviewCount: 89,
        onSale: false,
        weight: 0.15,
        brand: 'WellnessCorp',
        model: 'WC-MV-365',
        countryOfOrigin: 'United States',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 3.99,
            estimatedDays: 5
        }
    },
    {
        id: 28,
        sku: 'TOY-003',
        name: 'Puzzle Game',
        description: '1000-piece jigsaw puzzle featuring beautiful landscape artwork',
        category: ProductCategory.Toys,
        price: 19.99,
        inStock: true,
        tags: ['puzzle', 'jigsaw', 'landscape', '1000-piece'],
        createdDate: new Date(currentYear, 5, 8),
        lastModified: new Date(currentYear, 6, 14),
        stockQuantity: 145,
        stockStatus: StockStatus.InStock,
        rating: 4.4,
        reviewCount: 76,
        onSale: false,
        weight: 0.8,
        brand: 'PlaySmart',
        model: 'PS-PZ-1000',
        countryOfOrigin: 'Germany',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 4.99,
            estimatedDays: 6
        }
    },
    {
        id: 29,
        sku: 'AUTO-003',
        name: 'Tire Pressure Gauge',
        description: 'Digital tire pressure gauge with backlit display',
        category: ProductCategory.Automotive,
        price: 15.99,
        salePrice: 12.99,
        inStock: true,
        tags: ['tire', 'pressure', 'gauge', 'digital'],
        createdDate: new Date(currentYear, 7, 3),
        lastModified: new Date(currentYear, 8, 9),
        stockQuantity: 198,
        stockStatus: StockStatus.InStock,
        rating: 2.9,
        reviewCount: 134,
        onSale: true,
        weight: 0.18,
        brand: 'AutoPro',
        model: 'AP-TPG-DIG',
        countryOfOrigin: 'Taiwan',
        shipping: {
            method: ShippingMethod.Express,
            cost: 4.99,
            estimatedDays: 3
        }
    },
    {
        id: 30,
        sku: 'OFFICE-003',
        name: 'Standing Desk Converter',
        description: 'Adjustable standing desk converter for ergonomic workstation',
        category: ProductCategory.Office,
        price: 199.99,
        inStock: false,
        tags: ['standing', 'desk', 'converter', 'ergonomic'],
        createdDate: new Date(currentYear, 8, 25),
        lastModified: new Date(currentYear, 9, 30),
        stockQuantity: 0,
        stockStatus: StockStatus.Discontinued,
        rating: 1.8,
        reviewCount: 156,
        onSale: false,
        weight: 12.3,
        brand: 'OfficeComfort',
        model: 'OC-SDC-ADJ',
        countryOfOrigin: 'Taiwan',
        shipping: {
            method: ShippingMethod.Freight,
            cost: 39.99,
            estimatedDays: 12
        }
    },
    {
        id: 31,
        sku: 'FOOD-003',
        name: 'Honey Jar',
        description: 'Pure wildflower honey harvested from local beekeepers',
        category: ProductCategory.Food,
        price: 12.99,
        inStock: true,
        tags: ['honey', 'natural', 'wildflower', 'local'],
        createdDate: new Date(currentYear, 4, 3),
        lastModified: new Date(currentYear, 5, 8),
        stockQuantity: 234,
        stockStatus: StockStatus.InStock,
        rating: 4.8,
        reviewCount: 167,
        onSale: false,
        weight: 0.68,
        brand: 'BeanCraft',
        model: 'BC-HNY-500',
        countryOfOrigin: 'New Zealand',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 3.99,
            estimatedDays: 5
        }
    },
    {
        id: 32,
        sku: 'ELEC-005',
        name: 'Wireless Earbuds',
        description: 'True wireless earbuds with active noise cancellation',
        category: ProductCategory.Electronics,
        price: 149.99,
        salePrice: 119.99,
        inStock: true,
        tags: ['wireless', 'earbuds', 'noise-cancellation', 'true-wireless'],
        createdDate: new Date(currentYear, 6, 18),
        lastModified: new Date(currentYear, 7, 22),
        stockQuantity: 78,
        stockStatus: StockStatus.InStock,
        rating: 4.4,
        reviewCount: 312,
        onSale: true,
        weight: 0.06,
        brand: 'TechPower',
        model: 'TP-WE-ANC',
        countryOfOrigin: 'China',
        shipping: {
            method: ShippingMethod.Express,
            cost: 8.99,
            estimatedDays: 2
        }
    },
    {
        id: 33,
        sku: 'HEALTH-004',
        name: 'Fish Oil Capsules',
        description: 'Omega-3 fish oil supplements for heart and brain health',
        category: ProductCategory.Health,
        price: 24.99,
        inStock: false,
        tags: ['fish-oil', 'omega-3', 'heart', 'brain'],
        createdDate: new Date(currentYear, 2, 12),
        lastModified: new Date(currentYear, 3, 18),
        stockQuantity: 0,
        stockStatus: StockStatus.OutOfStock,
        rating: 3.4,
        reviewCount: 98,
        onSale: false,
        weight: 0.12,
        brand: 'WellnessCorp',
        model: 'WC-FO-1200',
        countryOfOrigin: 'United States',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 4.99,
            estimatedDays: 7
        }
    },
    {
        id: 34,
        sku: 'TOY-004',
        name: 'Board Game Set',
        description: 'Classic strategy board game for family entertainment',
        category: ProductCategory.Toys,
        price: 34.99,
        salePrice: 27.99,
        inStock: true,
        tags: ['board-game', 'strategy', 'family', 'classic'],
        createdDate: new Date(currentYear, 8, 7),
        lastModified: new Date(currentYear, 9, 14),
        stockQuantity: 112,
        stockStatus: StockStatus.InStock,
        rating: 4.6,
        reviewCount: 145,
        onSale: true,
        weight: 1.8,
        brand: 'TechToys',
        model: 'TT-BG-STR',
        countryOfOrigin: 'Germany',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 6.99,
            estimatedDays: 5
        }
    },
    {
        id: 35,
        sku: 'AUTO-004',
        name: 'Car Dash Cam',
        description: 'HD dashboard camera with night vision and loop recording',
        category: ProductCategory.Automotive,
        price: 89.99,
        salePrice: 74.99,
        inStock: true,
        tags: ['dashcam', 'hd', 'night-vision', 'recording'],
        createdDate: new Date(currentYear, 1, 5),
        lastModified: new Date(currentYear, 2, 12),
        stockQuantity: 45,
        stockStatus: StockStatus.InStock,
        rating: 3.5,
        reviewCount: 167,
        onSale: true,
        weight: 0.3,
        brand: 'AutoPro',
        model: 'AP-DC-HD',
        countryOfOrigin: 'Taiwan',
        shipping: {
            method: ShippingMethod.Express,
            cost: 9.99,
            estimatedDays: 3
        }
    },
    {
        id: 36,
        sku: 'BOOKS-003',
        name: 'Cooking Masterclass',
        description: 'Professional cooking techniques and recipes from renowned chefs',
        category: ProductCategory.Books,
        price: 45.99,
        inStock: true,
        tags: ['cooking', 'recipes', 'professional', 'techniques'],
        createdDate: new Date(currentYear, 10, 14),
        lastModified: new Date(currentYear, 11, 8),
        stockQuantity: 67,
        stockStatus: StockStatus.InStock,
        rating: 4.9,
        reviewCount: 234,
        onSale: false,
        weight: 0.8,
        brand: 'TechBooks',
        model: 'TB-CM-2024',
        countryOfOrigin: 'France',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 5.99,
            estimatedDays: 6
        }
    },
    {
        id: 37,
        sku: 'CLOTH-005',
        name: 'Leather Wallet',
        description: 'Genuine leather wallet with RFID blocking technology',
        category: ProductCategory.Clothing,
        price: 49.99,
        inStock: true,
        tags: ['leather', 'wallet', 'rfid', 'genuine'],
        createdDate: new Date(currentYear, 0, 22),
        lastModified: new Date(currentYear, 1, 28),
        stockQuantity: 189,
        stockStatus: StockStatus.InStock,
        rating: 4.3,
        reviewCount: 178,
        onSale: false,
        weight: 0.15,
        brand: 'EcoWear',
        model: 'ECO-LW-RFID',
        countryOfOrigin: 'Italy',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 4.99,
            estimatedDays: 4
        }
    },
    {
        id: 38,
        sku: 'HOME-004',
        name: 'Air Purifier',
        description: 'HEPA air purifier with smart sensors and app control',
        category: ProductCategory.HomeGarden,
        price: 249.99,
        salePrice: 199.99,
        inStock: false,
        tags: ['air-purifier', 'hepa', 'smart', 'sensors'],
        createdDate: new Date(currentYear, 3, 9),
        lastModified: new Date(currentYear, 4, 16),
        stockQuantity: 0,
        stockStatus: StockStatus.PreOrder,
        rating: 4.5,
        reviewCount: 189,
        onSale: true,
        weight: 6.8,
        brand: 'KitchenPro',
        model: 'KP-AP-HEPA',
        countryOfOrigin: 'Germany',
        shipping: {
            method: ShippingMethod.Freight,
            cost: 19.99,
            estimatedDays: 10
        }
    },
    {
        id: 39,
        sku: 'SPORTS-005',
        name: 'Resistance Bands Set',
        description: 'Complete resistance bands set with multiple resistance levels',
        category: ProductCategory.Sports,
        price: 24.99,
        inStock: true,
        tags: ['resistance', 'bands', 'exercise', 'fitness'],
        createdDate: new Date(currentYear, 7, 11),
        lastModified: new Date(currentYear, 8, 17),
        stockQuantity: 267,
        stockStatus: StockStatus.InStock,
        rating: 4.4,
        reviewCount: 123,
        onSale: false,
        weight: 0.9,
        brand: 'FitLife',
        model: 'FL-RB-SET',
        countryOfOrigin: 'India',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 5.99,
            estimatedDays: 5
        }
    },
    {
        id: 40,
        sku: 'OFFICE-004',
        name: 'Monitor Stand',
        description: 'Adjustable monitor stand with storage drawer and USB hub',
        category: ProductCategory.Office,
        price: 79.99,
        inStock: true,
        tags: ['monitor', 'stand', 'adjustable', 'storage'],
        createdDate: new Date(currentYear, 5, 25),
        lastModified: new Date(currentYear, 6, 30),
        stockQuantity: 134,
        stockStatus: StockStatus.InStock,
        rating: 4.2,
        reviewCount: 156,
        onSale: false,
        weight: 3.2,
        brand: 'OfficeComfort',
        model: 'OC-MS-USB',
        countryOfOrigin: 'Taiwan',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 12.99,
            estimatedDays: 7
        }
    },
    {
        id: 41,
        sku: 'ELEC-006',
        name: 'Tablet Stand',
        description: 'Universal tablet stand with adjustable angles and rotation',
        category: ProductCategory.Electronics,
        price: 19.99,
        salePrice: 15.99,
        inStock: true,
        tags: ['tablet', 'stand', 'universal', 'adjustable'],
        createdDate: new Date(currentYear, 9, 3),
        lastModified: new Date(currentYear, 10, 7),
        stockQuantity: 298,
        stockStatus: StockStatus.InStock,
        rating: 2.6,
        reviewCount: 89,
        onSale: true,
        weight: 0.35,
        brand: 'TechPower',
        model: 'TP-TS-360',
        countryOfOrigin: 'South Korea',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 3.99,
            estimatedDays: 4
        }
    },
    {
        id: 42,
        sku: 'FOOD-004',
        name: 'Olive Oil',
        description: 'Extra virgin olive oil cold-pressed from Mediterranean olives',
        category: ProductCategory.Food,
        price: 18.99,
        inStock: true,
        tags: ['olive-oil', 'extra-virgin', 'cold-pressed', 'mediterranean'],
        createdDate: new Date(currentYear, 11, 12),
        lastModified: new Date(currentYear, 11, 28),
        stockQuantity: 156,
        stockStatus: StockStatus.InStock,
        rating: 4.7,
        reviewCount: 201,
        onSale: false,
        weight: 0.75,
        brand: 'BeanCraft',
        model: 'BC-OO-EV',
        countryOfOrigin: 'Greece',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 4.99,
            estimatedDays: 5
        }
    },
    {
        id: 43,
        sku: 'HEALTH-005',
        name: 'Probiotics Supplement',
        description: 'Multi-strain probiotic supplement for digestive health',
        category: ProductCategory.Health,
        price: 34.99,
        salePrice: 27.99,
        inStock: true,
        tags: ['probiotics', 'digestive', 'multi-strain', 'supplement'],
        createdDate: new Date(currentYear, 4, 7),
        lastModified: new Date(currentYear, 5, 13),
        stockQuantity: 89,
        stockStatus: StockStatus.InStock,
        rating: 4.3,
        reviewCount: 134,
        onSale: true,
        weight: 0.1,
        brand: 'HealthPlus',
        model: 'HP-PRO-30',
        countryOfOrigin: 'Canada',
        shipping: {
            method: ShippingMethod.Express,
            cost: 6.99,
            estimatedDays: 2
        }
    },
    {
        id: 44,
        sku: 'TOY-005',
        name: 'Action Figure',
        description: 'Collectible action figure with articulated joints and accessories',
        category: ProductCategory.Toys,
        price: 29.99,
        inStock: false,
        tags: ['action-figure', 'collectible', 'articulated', 'accessories'],
        createdDate: new Date(currentYear, 6, 16),
        lastModified: new Date(currentYear, 7, 21),
        stockQuantity: 0,
        stockStatus: StockStatus.BackOrder,
        rating: 4.8,
        reviewCount: 178,
        onSale: false,
        weight: 0.4,
        brand: 'PlaySmart',
        model: 'PS-AF-001',
        countryOfOrigin: 'Japan',
        shipping: {
            method: ShippingMethod.Express,
            cost: 7.99,
            estimatedDays: 14
        }
    },
    {
        id: 45,
        sku: 'AUTO-005',
        name: 'Jump Starter',
        description: 'Portable car jump starter with power bank functionality',
        category: ProductCategory.Automotive,
        price: 129.99,
        inStock: true,
        tags: ['jump-starter', 'portable', 'power-bank', 'emergency'],
        createdDate: new Date(currentYear, 8, 20),
        lastModified: new Date(currentYear, 9, 25),
        stockQuantity: 56,
        stockStatus: StockStatus.InStock,
        rating: 4.5,
        reviewCount: 167,
        onSale: false,
        weight: 1.8,
        brand: 'CarTech',
        model: 'CT-JS-12V',
        countryOfOrigin: 'China',
        shipping: {
            method: ShippingMethod.Express,
            cost: 11.99,
            estimatedDays: 3
        }
    },
    {
        id: 46,
        sku: 'BOOKS-004',
        name: 'Fitness Guide',
        description: 'Complete fitness and nutrition guide for healthy lifestyle',
        category: ProductCategory.Books,
        price: 19.99,
        salePrice: 16.99,
        inStock: true,
        tags: ['fitness', 'nutrition', 'health', 'lifestyle'],
        createdDate: new Date(currentYear, 0, 30),
        lastModified: new Date(currentYear, 2, 6),
        stockQuantity: 178,
        stockStatus: StockStatus.InStock,
        rating: 3.7,
        reviewCount: 145,
        onSale: true,
        weight: 0.4,
        brand: 'TechBooks',
        model: 'TB-FG-2024',
        countryOfOrigin: 'United States',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 3.99,
            estimatedDays: 5
        }
    },
    {
        id: 47,
        sku: 'CLOTH-006',
        name: 'Baseball Cap',
        description: 'Adjustable baseball cap with embroidered logo',
        category: ProductCategory.Clothing,
        price: 22.99,
        inStock: true,
        tags: ['baseball', 'cap', 'adjustable', 'embroidered'],
        createdDate: new Date(currentYear, 2, 18),
        lastModified: new Date(currentYear, 3, 24),
        stockQuantity: 245,
        stockStatus: StockStatus.InStock,
        rating: 3.3,
        reviewCount: 98,
        onSale: false,
        weight: 0.12,
        brand: 'EcoWear',
        model: 'ECO-BC-001',
        countryOfOrigin: 'Bangladesh',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 3.99,
            estimatedDays: 6
        }
    },
    {
        id: 48,
        sku: 'HOME-005',
        name: 'Vacuum Cleaner',
        description: 'Cordless stick vacuum with HEPA filtration and LED lights',
        category: ProductCategory.HomeGarden,
        price: 199.99,
        inStock: false,
        tags: ['vacuum', 'cordless', 'hepa', 'led'],
        createdDate: new Date(currentYear, 5, 2),
        lastModified: new Date(currentYear, 6, 8),
        stockQuantity: 0,
        stockStatus: StockStatus.Discontinued,
        rating: 4.6,
        reviewCount: 289,
        onSale: false,
        weight: 2.8,
        brand: 'GreenTech',
        model: 'GT-VC-CORD',
        countryOfOrigin: 'Netherlands',
        shipping: {
            method: ShippingMethod.Freight,
            cost: 15.99,
            estimatedDays: 8
        }
    },
    {
        id: 49,
        sku: 'SPORTS-006',
        name: 'Water Bottle',
        description: 'Insulated stainless steel water bottle with leak-proof lid',
        category: ProductCategory.Sports,
        price: 24.99,
        salePrice: 19.99,
        inStock: true,
        tags: ['water-bottle', 'insulated', 'stainless-steel', 'leak-proof'],
        createdDate: new Date(currentYear, 10, 8),
        lastModified: new Date(currentYear, 11, 14),
        stockQuantity: 312,
        stockStatus: StockStatus.InStock,
        rating: 4.7,
        reviewCount: 234,
        onSale: true,
        weight: 0.45,
        brand: 'SportsPro',
        model: 'SP-WB-INS',
        countryOfOrigin: 'Japan',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 4.99,
            estimatedDays: 4
        }
    },
    {
        id: 50,
        sku: 'OFFICE-005',
        name: 'Desk Organizer',
        description: 'Bamboo desk organizer with multiple compartments and phone stand',
        category: ProductCategory.Office,
        price: 39.99,
        salePrice: 29.99,
        inStock: true,
        tags: ['desk', 'organizer', 'bamboo', 'compartments'],
        createdDate: new Date(currentYear, 7, 29),
        lastModified: new Date(currentYear, 8, 4),
        stockQuantity: 167,
        stockStatus: StockStatus.InStock,
        rating: 3.9,
        reviewCount: 123,
        onSale: true,
        weight: 1.2,
        brand: 'OfficeComfort',
        model: 'OC-DO-BAMB',
        countryOfOrigin: 'Vietnam',
        shipping: {
            method: ShippingMethod.Standard,
            cost: 6.99,
            estimatedDays: 5
        }
    }
];
